#!/bin/bash
DN=$(dirname "$0")

pushd "${DN}" &>/dev/null

  rm -rf node_modules/
  rm -f package-lock.json
  rm -rf platforms/*
  rm -rf hooks/

  npm install
  npm install --save-dev nativescript-dev-webpack
  "${DN}/node_modules/.bin/update-ns-webpack" --configs --deps
  tns update
  tns prepare android

popd
